# 멜론 인기곡 데이터 수집 및 분석

In [24]:
import chromedriver_autoinstaller
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

In [14]:
chromedriver_autoinstaller.install()

'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromedriver_autoinstaller\\145\\chromedriver.exe'

In [20]:
browser = webdriver.Chrome()

In [21]:
url = 'https://www.melon.com/chart/index.htm'
browser.get(url)

In [22]:
html = browser.page_source

In [26]:
soup = BeautifulSoup(html, 'html.parser')

In [27]:
soup

<html class="narrow-screen" lang="ko"><head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<title>멜론차트&gt;TOP100&gt;멜론</title>
<meta content="음악서비스, 멜론차트, 멜론TOP100, 최신음악, 인기가요, 뮤직비디오, 앨범, 플레이어, 스트리밍, 다운로드, 아티스트플러스, 아티스트채널" name="keywords"/>
<meta content="No.1 뮤직플랫폼 멜론! 최신 트렌드부터 나를 아는 똑똑한 음악추천까지!" name="description"/>
<meta content="ee85ff6db1fa8f2226bcb671ecb2bcdbcffb6f8b" name="naver-site-verification"/>
<meta content="q4tbTQhmxa4La3OdNLsNOCxrJ_WV6lUlBFrFW4-HqQc" name="google-site-verification"/>
<meta content="4022717807957185" property="fb:app_id"/>
<meta content="Melon" property="og:title"/>
<meta content="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" property="og:image"/>
<meta content="음악이 필요한 순간, 멜론" property="og:description"/>
<meta content="http://www.melon.com/chart/index.htm" property="og:url"/>
<meta content="website" property="og:type"/>
<meta content="멜론" property="og:site_name"/>
<meta content="width=device-width" name="viewport"/>
<link href="/favicon.ico?2" id="favicon" rel="shortcut icon" type="image/x-icon"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/p9/h/avqof8c9.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/l8/i/bmqlrmeyi7uljr5.css" rel="stylesheet" type="text/css"/>
<!-- 댓글 css 파일 네임 변경 -->
<!--멜론혜택 페이지 댓글 css 예외처리-->
<link href="https://static.melon.co.kr/static/web/resource/style/w1/dn/4/ynesuqe51i.css" rel="stylesheet" type="text/css"/>
<link href="/resource/style/web/chart/melonweb_chart_4x.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/qa/5/rlbqwv6hljdyw.css" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:400" rel="stylesheet"/>
<script src="/resource/script/cds/common/web/member_api.js?_resVer=b4ce10a86ee7524c9e7d2d38ad43a769" type="text/javascript"></script>
<script src="/resource/script/cds/common/web/commerce_api.js?_resVer=3be4a69429902f23e7b988e16b9090ad" type="text/javascript"></script>
<script src="/resource/script/web/common/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="https://member.melon.com/resource/script/web/member/melonweb_member_external.js?tm=20260304" type="text/javascript"></script>
<script src="https://static.melon.co.kr/static/web/resource/script/w1/c1/d/7j9pwitvgh7.js" type="text/javascript"></script>
<script type="text/javascript">
	(function() {
		WEBPOCIMG = {
			defaultImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				var thumbType = "_500";
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultAlbumImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultArtistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultDjImg : function(obj){
			},
			defaultMvImg : function(obj, width, height){
				if(width == null || width == '') width = $(obj).width();
				if(height == null || height == '') height = $(obj).height();

				var ratio43 = Math.floor((4/3)*10)/10;
				var ratio169 = Math.floor((16/9)*10)/10;
				var ratioObj = Math.floor((width/height)*10)/10;

				var ratio = "4x3";
				if(ratioObj == ratio43){
					ratio = "4x3"; //contentsType = "mv43";
				} else if(ratioObj == ratio169){
					ratio = "16x9"; //contentsType = "mv169";
				} else {
					if(ratioObj > 1.5) ratio = "16x9";
					else ratio = "4x3";
				}

				if(width == 0) width = 640;
				if(height == 0) ratio = "16x9";

				//가장 큰사이즈로 리사이즈함
				var thumbType = "_" + ratio + "_640";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noMovie" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPlaylistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultMemberImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPhotoImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShopImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 256;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_256";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noProduct" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShowwingImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noShowing" + thumbType + ".jpg";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultTicketImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noTicket" + thumbType + ".png";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultSmartRadioImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noSmartradio_59_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultConcertImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum_114_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			}
		}
		,WEBELLIPSIS = {
			ellipsis : function(ellipsisName,moreClassName,eWidth){
		        //아티스트 더보기
		        var arObj = $('.' + ellipsisName);
		        for(var i = 0; i < arObj.length; i++){
		            if (arObj.eq(i).width() > eWidth ){
		                arObj.eq(i).parent().parent().parent().find('.' + moreClassName).show();
		            }
		        }
			}
		}
	})();
	</script>
</head>
<body>
<div id="wrap">
<div id="skip_nav">skip navigation
		<ul>
<li><a href="#gnb_menu">메뉴</a></li>
<li><a href="#conts_section">본문</a></li>
<li><a href="#footer">하단 정보</a></li>
</ul>
</div>
<!--  header -->
<div class="gnb2_expn" id="header">
<div class="my_fold" id="header_wrap"> <!-- 1024이상 마이영역 접었을때 클래스 my_fold 추가 -->
<div class="clfix" id="gnb">
<!-- 상단 빠른 메뉴 -->
<div id="util_menu">
<p class="none">상단 빠른 메뉴</p>
<div class="top_left">
<ul class="menu-list">
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V08&amp;ACTION_AF_CLICK=V1" href="//ticket.melon.com/main/index.htm" title="멜론티켓"><span>멜론티켓</span></a></li>
</ul>
</div>
<!-- 140603_수정 -->
<div class="top_right">
<ul class="menu-list">
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B01&amp;ACTION_AF_CLICK=V1" href="/commerce/pamphlet/web/sale_listMainView.htm" title="이용권구매"><span>이용권구매</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V06&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/benefit/lounge/main.htm" title="멜론혜택"><span>멜론혜택</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B03&amp;ACTION_AF_CLICK=V1" href="/event/list.htm" title="이벤트"><span>이벤트</span></a></li>
<li><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V02&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/customer/announce/index.htm" title="공지사항"><span>공지사항</span></a></li>
</ul>
<script type="text/javascript">
							var html = '';
							var logoutReturnUrl = window.location.href;

							if(logoutReturnUrl == ''){
								logoutReturnUrl = 'www.melon.com';
							}

							if(isMelonLogin()){

								var memberKey = getMemberKey()
								var memberInfo = svcMember.displayIdByMemberKey(memberKey);
								var memberType = svcMember.getMemberType().MEMBERTYPE;
								var gradeInfo = svcMember.gradeInfoByMemberKey(memberKey);

								var memId = '';
								if(memberType == undefined || memberType == null){
									memberType = '0';
								}

								if(memberInfo.DISPLAYID != undefined || memberInfo.DISPLAYID != null){
									memId = memberInfo.DISPLAYID;
								}

								if(memId.indexOf("@") != -1 && memberType != '1'){//카카오계정이 아닌경우에만 @도메인 영역 삭제처리
									memId = memId.split("@")[0];
								}

								var fromMPS = getCookie("MPS"); // 멜론 플레이어에서 왔는지 확인.
								var fromMPSYn = fromMPS == null || fromMPS.indexOf("MELONPLAYER") < 0;

								var gradeImg = "";
								var gradeName = gradeInfo.GRADE;

								if(gradeName == undefined || gradeName == null){
									gradeName = '일반';
								}


								try {
									if(gradeName == '일반'){
										gradeImg = "";
									} else if(gradeName == 'GREEN'){
										gradeImg = "<span class=\"icon-comm grade-green\"></span>";
									} else if(gradeName == 'SILVER'){
										gradeImg = "<span class=\"icon-comm grade-silver\"></span>";
									} else if(gradeName == 'GOLD'){
										gradeImg = "<span class=\"icon-comm grade-gold\"></span>";
									} else if(gradeName == 'VIP'){
										gradeImg = "<span class=\"icon-comm grade-vip\"></span>";
									} else if(gradeName == 'MVIP'){
										gradeImg = "<span class=\"icon-comm grade-mvip\"></span>";
									}

									//카카오연동확인
									if(memberType == '1'){
										gradeImg += "<span class=\"icon-comm icon-kakao\"></span>";
									}

								} catch (e) {}

								var logoutButtonHtml = '<button type="button" title="로그아웃" class="btn_top_logout" onclick="javascript:MELON.WEBSVC.POC.logout(\'\');">로그아웃</button>';

								html = ['<div class="header_login">',
									' <span class="icon_grade">',
									'' + gradeImg + '',
									' </span>',
									' <span class="wrap_id"><a href="javascript:location.href=_getHttpsMemberDomain()+ \'/muid/web/help/myinfointro_inform.htm\';" class="user_id"><strong>' + memId + '</strong>님</a></span>',
									fromMPSYn ? logoutButtonHtml : '', //멜론 플레이어에서 로그아웃 싱크 안맞는 이슈로 인해 로그아웃 멜론 플레이어에서 왔을 시 버튼 제거
									'</div>'
								].join('');
								document.write(html);
							}
						</script>
</div>
<!-- //140603_수정 -->
</div>
<!-- //상단 빠른 메뉴 -->
<div class="header-utils">
<h1 class="logo">
<a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=M01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/index.htm" title="Melon 홈으로 이동"><span class="screen-out">Melon</span></a>
</h1>
<!-- 통합검색 영역 -->
<fieldset>
<legend>통합검색영역</legend>
<input autocomplete="off" class="ui-autocomplete-input" id="top_search" name="" onkeypress="if(event.keyCode == 13){goSearch();}" placeholder="" style="display: block;" title="검색 입력 편집창" type="text"/><span aria-live="polite" class="ui-helper-hidden-accessible" role="status"></span><input id="keywordLink" name="keywordLink" type="hidden" value="https://www.melon.com/masterpiece/timeline.htm?WLFC=4SEARCH"/>
<button class="btn_icon btn_auto close" id="top_search_autocomplete_toggle" style="display: none;" title="자동검색 펼침" type="button"><span class="odd_span">자동검색 펼침</span></button> <!-- open/close 클래스 사용 -->
<button class="btn_icon search_m" title="검색" type="button"><span class="odd_span">검색</span></button>
<div class="auto_complete" id="top_search_autocomplete"><div class="auto_complete_cont" style="display:block;"><!-- 자동완성 레이어 --></div><ul class="ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all" id="ui-id-1" style="display: none;" tabindex="0"></ul></div>
<div class="auto_complete" id="top_search_autocomplete_template" style="display: none;"> <!-- 자동완성 레이어 템플릿 -->
<!-- 텍스트 결과 -->
<ul class="text_result">
<li><a class="autocomplete-label" href="#"></a></li>
</ul>
<!-- 섬네일 결과 -->
<ul class="thumb_result">
<li class="cate"></li>
<li class="class02">
<a href="#">
<span class="thumb_40">
<span class="thumb_frame"></span>
<img alt="" class="autocomplete-img" height="40" width="40"/>
</span>
<div class="info">
<span class="autocomplete-label"></span><br/>
<span><span class="f11 autocomplete-info"></span></span>
</div>
</a>
</li>
</ul>
<!-- 검색어가 없을 때 -->
<ul class="text_result">
<li class="result_none">
<span>해당글자로 시작하는 단어가 없습니다.</span>
</li>
</ul>
</div>
</fieldset>
<form action="" id="searchFrm" method="get" style="display: none">
<input name="q" type="hidden"/>
<input name="section" type="hidden"/>
</form>
<!-- //통합검색 영역 -->
<!-- 실시간 검색어 -->
<div class="realtime_soar_keyword">
<!-- 140519_수정 -->
<a class="title" href="#none" style="display: inline-block;">인기 검색어</a>
<!-- //140519_수정 -->
<div class="keyword_overlay">
<ol style="overflow:hidden;">
<!-- 롤링 영역 -->
<li>
<strong class="order bg1 on">1<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('테이','','searchFrm','','hot_kwd');" title="테이 - 페이지 이동">테이</a>
<span class="wrap_rank up"> <span class="icon">순위상승수</span> <span class="num">1</span> </span>
</li>
<li style="display:none">
<strong class="order bg2">2<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('에픽하이 (EPIK HIGH)','','searchFrm','','hot_kwd');" title="에픽하이 (EPIK HIGH) - 페이지 이동">에픽하이 (EPIK HIGH)</a>
<span class="wrap_rank up"> <span class="icon">순위상승수</span> <span class="num">19</span> </span>
</li>
<li style="display:none">
<strong class="order bg3">3<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('미스트롯4','','searchFrm','','hot_kwd');" title="미스트롯4 - 페이지 이동">미스트롯4</a>
<span class="wrap_rank up"> <span class="icon">순위상승수</span> <span class="num">2</span> </span>
</li>
<li style="display:none">
<strong class="order bg4">4<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('지코 (ZICO)','','searchFrm','','hot_kwd');" title="지코 (ZICO) - 페이지 이동">지코 (ZICO)</a>
<span class="wrap_rank up"> <span class="icon">순위상승수</span> <span class="num">18</span> </span>
</li>
<li style="display:none">
<strong class="order bg5">5<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('싸이 (PSY)','','searchFrm','','hot_kwd');" title="싸이 (PSY) - 페이지 이동">싸이 (PSY)</a>
<span class="wrap_rank up"> <span class="icon">순위상승수</span> <span class="num">8</span> </span>
</li>
<li style="display:none">
<strong class="order bg6">6<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('한로로','','searchFrm','','hot_kwd');" title="한로로 - 페이지 이동">한로로</a>
<span class="wrap_rank up"> <span class="icon">순위상승수</span> <span class="num">2</span> </span>
</li>
<!-- 감소-->
<li style="display:none">
<strong class="order bg7">7<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('이승기','','searchFrm','','hot_kwd');" title="이승기 - 페이지 이동">이승기</a>
<span class="wrap_rank down"> <span class="icon">순위하락수</span> <span class="num">3</span> </span>
</li>
<!-- 감소-->
<li style="display:none">
<strong class="order bg8">8<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('이영지','','searchFrm','','hot_kwd');" title="이영지 - 페이지 이동">이영지</a>
<span class="wrap_rank down"> <span class="icon">순위하락수</span> <span class="num">5</span> </span>
</li>
<li style="display:none">
<strong class="order bg9">9<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('나무','','searchFrm','','hot_kwd');" title="나무 - 페이지 이동">나무</a>
<span class="wrap_rank new"> <span class="icon">새진입</span> </span>
</li>
<li style="display:none">
<strong class="order bg10">10<span class="none"> 위</span></strong>
<a class="ellipsis" href="javascript:melon.link.goTotalSearch('SG 워너비','','searchFrm','','hot_kwd');" title="SG 워너비 - 페이지 이동">SG 워너비</a>
<span class="wrap_rank new"> <span class="icon">새진입</span> </span>
</li>
<!-- //롤링 영역 -->
</ol>
<!-- 140423_추가 -->
<!-- //140423_추가 -->
</div>
</div>
<!-- //실시간 검색어 -->
<!-- 배너 영역 -->
<div class="cmn_banner">
<!-- 랜덤으로 뿌릴 것 -->
</div>
</div>
</div>
<!-- 140314_gnb마크업 수정 -->
<div id="gnb_menu">
<ul>
<li class="nth1 on">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=R01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/chart/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu01">멜론차트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child on"><a href="//www.melon.com/chart/index.htm"><span class="menu_chart m1">TOP100</span></a></li>
<li class=""><a href="//www.melon.com/chart/hot100/index.htm"><span class="menu_chart m6">HOT100</span></a></li><!-- // MELONUIT-2465 -->
<li class=""><a href="//www.melon.com/chart/day/index.htm"><span class="menu_chart m2">일간</span></a></li>
<li class=""><a href="//www.melon.com/chart/week/index.htm"><span class="menu_chart m3">주간</span></a></li>
<li class=""><a href="//www.melon.com/chart/month/index.htm"><span class="menu_chart m4">월간</span></a></li>
<li class=""><a href="//www.melon.com/chart/age/index.htm"><span class="menu_chart m5">시대</span></a></li>
</ul>
<div class="chart_finder">
<button class="btn_chart_f" onclick="location.href='//www.melon.com/chart/search/index.htm'" type="button"><span class="odd_span">차트 파인더</span></button>
</div>
</div>
</li>
<li class="nth2">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/new/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu02">최신음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/new/index.htm"><span class="menu_new m1">최신곡</span></a></li>

In [31]:
lst = soup.select('tr.lst50')
lst

[<tr class="lst50" data-song-no="601237102" id="lst50">
 <td><div class="wrap t_right"><input class="input_check" name="input_check" title="BANG BANG 곡 선택" type="checkbox" value="601237102"/></div></td>
 <td><div class="wrap t_center"><span class="rank">1</span><span class="none">위</span></div></td>
 <!-- 차트순위 추가 -->
 <td><div class="wrap">
 <span class="rank_wrap" title="순위 동일">
 <span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
 <span class="none">0</span>
 </span>
 </div></td>
 <td><div class="wrap">
 <a class="image_typeAll" href="/album/detail.htm?albumId=12845274" title="REVIVE+">
 <img alt="REVIVE+ - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/128/45/274/12845274_20260223113048_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>
 </div></td>
 <td><div class="wrap">
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=601237102" title="BANG BANG 곡정보"><span class="none">곡정보</span></a>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank01"><span>
 <a href="javascript:melon.play.playSong('1000002721',601237102);" title="BANG BANG 재생">BANG BANG</a>
 </span></div><br/>
 <div class="ellipsis rank02">
 <a href="/artist/timeline.htm?artistId=3055146" title="IVE (아이브) - 페이지 이동">IVE (아이브)</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=3055146" title="IVE (아이브) - 페이지 이동">IVE (아이브)</a></span>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank03">
 <a href="/album/detail.htm?albumId=12845274" title="REVIVE+ - 페이지 이동">REVIVE+</a>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <button class="button_etc like" data-song-menuid="1000002721" data-song-no="601237102" title="BANG BANG 좋아요" type="button"><span class="odd_span">좋아요</span>
 <span class="cnt">
 <span class="none">총건수</span>
 45,547</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons play" onclick="melon.play.playSong('1000002721',601237102);" title="듣기" type="button"><span class="none">듣기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons scrap" onclick="melon.play.addPlayList('601237102');" title="담기" type="button"><span class="none">담기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '601237102', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons video" onclick="melon.link.goMvDetail('1000002721', '601237102','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
 </div></td>
 </tr>,
 <tr class="lst50" data-song-no="601013499" id="lst50">
 <td><div class="wrap t_right"><input class="input_check" name="input_check" title="404 (New Era) 곡 선택" type="checkbox" value="601013499"/></div></td>
 <td><div class="wrap t_center"><span class="rank">2</span><span class="none">위</span></div></td>
 <!-- 차트순위 추가 -->
 <td><div class="wrap">
 <span class="rank_wrap" title="순위 동일">
 <span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
 <span class="none">0</span>
 </span>
 </div></td>
 <td><div class="wrap">
 <a class="image_typeAll" href="/album/detail.htm?albumId=12806237" title="Delulu Pack">
 <img alt="Delulu Pack - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/128/06/237/12806237_20260126145002_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>
 </div></td>
 <td><div class="wrap">
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=601013499" title="404 (New Era) 곡정보"><span class="none">곡정보</span></a>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank01"><span>
 <a href="javascript:melon.play.playSong('1000002721',601013499);" title="404 (New Era) 재생">404 (New Era)</a>
 </span></div><br/>
 <div class="ellipsis rank02">
 <a href="/artist/timeline.htm?artistId=4099078" title="KiiiKiii (키키) - 페이지 이동">KiiiKiii (키키)</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=4099078" title="KiiiKiii (키키) - 페이지 이동">KiiiKiii (키키)</a></span>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank03">
 <a href="/album/detail.htm?albumId=12806237" title="Delulu Pack - 페이지 이동">Delulu Pack</a>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <button class="button_etc like" data-song-menuid="1000002721" data-song-no="601013499" title="404 (New Era) 좋아요" type="button"><span class="odd_span">좋아요</span>
 <span class="cnt">
 <span class="none">총건수</span>
 46,528</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons play" onclick="melon.play.playSong('1000002721',601013499);" title="듣기" type="button"><span class="none">듣기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons scrap" onclick="melon.play.addPlayList('601013499');" title="담기" type="button"><span class="none">담기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '601013499', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons video" onclick="melon.link.goMvDetail('1000002721', '601013499','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
 </div></td>
 </tr>,
 <tr class="lst50" data-song-no="600287375" id="lst50">
 <td><div class="wrap t_right"><input class="input_check" name="input_check" title="Good Goodbye 곡 선택" type="checkbox" value="600287375"/></div></td>
 <td><div class="wrap t_center"><span class="rank">3</span><span class="none">위</span></div></td>
 <!-- 차트순위 추가 -->
 <td><div class="wrap">
 <span class="rank_wrap" title="순위 동일">
 <span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
 <span class="none">0</span>
 </span>
 </div></td>
 <td><div class="wrap">
 <a class="image_typeAll" href="/album/detail.htm?albumId=12160000" title="Good Goodbye">
 <img alt="Good Goodbye - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/121/60/000/12160000_20251014164646_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>
 </div></td>
 <td><div class="wrap">
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=600287375" title="Good Goodbye 곡정보"><span class="none">곡정보</span></a>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank01"><span>
 <a href="javascript:melon.play.playSong('1000002721',600287375);" title="Good Goodbye 재생">Good Goodbye</a>
 </span></div><br/>
 <div class="ellipsis rank02">
 <a href="/artist/timeline.htm?artistId=756531" title="화사 (HWASA) - 페이지 이동">화사 (HWASA)</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=756531" title="화사 (HWASA) - 페이지 이동">화사 (HWASA)</a></span>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank03">
 <a href="/album/detail.htm?albumId=12160000" title="Good Goodbye - 페이지 이동">Good Goodbye</a>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <button class="button_etc like" data-song-menuid="1000002721" data-song-no="600287375" title="Good Goodbye 좋아요" type="button"><span class="odd_span">좋아요</span>
 <span class="cnt">
 <span class="none">총건수</span>
 113,432</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons play" onclick="melon.play.playSong('1000002721',600287375);" title="듣기" type="button"><span class="none">듣기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons scrap" onclick="melon.play.addPlayList('600287375');" title="담기" type="button"><span class="none">담기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '600287375', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons video" onclick="melon.link.goMvDetail('1000002721', '600287375','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
 </div></td>
 </tr>,
 <tr class="lst50" data-song-no="601332163" id="lst50">
 <td><div class="wrap t_right"><input class="input_check" name="input_check" title="RUDE! 곡 선택" type="checkbox" value="601332163"/></div></td>
 <td><div class="wrap t_center"><span class="rank">4</span><span class="none">위</span></div></td>
 <!-- 차트순위 추가 -->
 <td><div class="wrap">
 <span class="rank_wrap" title="순위 동일">
 <span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
 <span class="none">0</span>
 </span>
 </div></td>
 <td><div class="wrap">
 <a class="image_typeAll" href="/album/detail.htm?albumId=12869629" title="RUDE!">
 <img alt="RUDE! - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/128/69/629/12869629_20260219143819_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>
 </div></td>
 <td><div class="wrap">
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=601332163" title="RUDE! 곡정보"><span class="none">곡정보</span></a>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank01"><span>
 <a href="javascript:melon.play.playSong('1000002721',601332163);" title="RUDE! 재생">RUDE!</a>
 </span></div><br/>
 <div class="ellipsis rank02">
 <a href="/artist/timeline.htm?artistId=4096106" title="Hearts2Hearts (하츠투하츠) - 페이지 이동">Hearts2Hearts (하츠투하츠)</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=4096106" title="Hearts2Hearts (하츠투하츠) - 페이지 이동">Hearts2Hearts (하츠투하츠)</a></span>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank03">
 <a href="/album/detail.htm?albumId=12869629" title="RUDE! - 페이지 이동">RUDE!</a>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <button class="button_etc like" data-song-menuid="1000002721" data-song-no="601332163" title="RUDE! 좋아요" type="button"><span class="odd_span">좋아요</span>
 <span class="cnt">
 <span class="none">총건수</span>
 27,232</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons play" onclick="melon.play.playSong('1000002721',601332163);" title="듣기" type="button"><span class="none">듣기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons scrap" onclick="melon.play.addPlayList('601332163');" title="담기" type="button"><span class="none">담기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '601332163', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons video" onclick="melon.link.goMvDetail('1000002721', '601332163','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
 </div></td>
 </tr>,
 <tr class="lst50" data-song-no="36730261" id="lst50">
 <td><div class="wrap t_right"><input class="input_check" name="input_check" title="사랑하게 될 거야 곡 선택" type="checkbox" value="36730261"/></div></td>
 <td><div class="wrap t_center"><span class="rank">5</span><span class="none">위</span></div></td>
 <!-- 차트순위 추가 -->
 <td><div class="wrap">
 <span class="rank_wrap" title="순위 동일">
 <span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
 <span class="none">0</span>
 </span>
 </div></td>
 <td><div class="wrap">
 <a class="image_typeAll" href="/album/detail.htm?albumId=11312872" title="이상비행">
 <img alt="이상비행 - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/113/12/872/11312872_20230823162414_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>
 </div></td>
 <td><div class="wrap">
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=36730261" title="사랑하게 될 거야 곡정보"><span class="none">곡정보</span></a>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank01"><span>
 <a href="javascript:melon.play.playSong('1000002721',36730261);" title="사랑하게 될 거야 재생">사랑하게 될 거야</a>
 </span></div><br/>
 <div class="ellipsis rank02">
 <a href="/artist/timeline.htm?artistId=3080810" title="한로로 - 페이지 이동">한로로</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=3080810" title="한로로 - 페이지 이동">한로로</a></span>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank03">
 <a href="/album/detail.htm?albumId=11312872" title="이상비행 - 페이지 이동">이상비행</a>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <button class="button_etc like" data-song-menuid="1000002721" data-song-no="36730261" title="사랑하게 될 거야 좋아요" type="button"><span class="odd_span">좋아요</span>
 <span class="cnt">
 <span class="none">총건수</span>
 110,317</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons play" onclick="melon.play.playSong('1000002721',36730261);" title="듣기" type="button"><span class="none">듣기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons scrap" onclick="melon.play.addPlayList('36730261');" title="담기" type="button"><span class="none">담기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '36730261', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons video disabled" disabled="disabled" onclick="melon.link.goMvDetail('1000002721', '36730261','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
 </div></td>
 </tr>,
 <tr class="lst50" data-song-no="36397952" id="lst50">
 <td><div class="wrap t_right"><input class="input_check" name="input_check" title="Drowning 곡 선택" type="checkbox" value="36397952"/></div></td>
 <td><div class="wrap t_center"><span class="rank">6</span><span class="none">위</span></div></td>
 <!-- 차트순위 추가 -->
 <td><div class="wrap">
 <span class="rank_wrap" title="순위 동일">
 <span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
 <span class="none">0</span>
 </span>
 </div></td>
 <td><div class="wrap">
 <a class="image_typeAll" href="/album/detail.htm?albumId=11183506" title="OO-LI">
 <img alt="OO-LI - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/111/83/506/11183506_20230426141236_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>
 </div></td>
 <td><div class="wrap">
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=36397952" title="Drowning 곡정보"><span class="none">곡정보</span></a>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank01"><span>
 <a href="javascript:melon.play.playSong('1000002721',36397952);" title="Drowning 재생">Drowning</a>
 </span></div><br/>
 <div class="ellipsis rank02">
 <a href="/artist/timeline.htm?artistId=2086047" title="WOODZ - 페이지 이동">WOODZ</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=2086047" title="WOODZ - 페이지 이동">WOODZ</a></span>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank03">
 <a href="/album/detail.htm?albumId=11183506" title="OO-LI - 페이지 이동">OO-LI</a>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <button class="button_etc like" data-song-menuid="1000002721" data-song-no="36397952" title="Drowning 좋아요" type="button"><span class="odd_span">좋아요</span>
 <span class="cnt">
 <span class="none">총건수</span>
 289,189</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons play" onclick="melon.play.playSong('1000002721',36397952);" title="듣기" type="button"><span class="none">듣기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons scrap" onclick="melon.play.addPlayList('36397952');" title="담기" type="button"><span class="none">담기</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '36397952', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons video disabled" disabled="disabled" onclick="melon.link.goMvDetail('1000002721', '36397952','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
 </div></td>
 </tr>,
 <tr class="lst50" data-song-no="33241003" id="lst50">
 <td><div class="wrap t_right"><input class="input_check" name="input_check" title="그대 작은 나의 세상이 되어 곡 선택" type="checkbox" value="33241003"/></div></td>
 <td><div class="wrap t_center"><span class="rank">7</span><span class="none">위</span></div></td>
 <!-- 차트순위 추가 -->
 <td><div class="wrap">
 <span class="rank_wrap" title="순위 동일">
 <span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
 <span class="none">0</span>
 </span>
 </div></td>
 <td><div class="wrap">
 <a class="image_typeAll" href="/album/detail.htm?albumId=10554647" title="부재">
 <img alt="부재 - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/105/54/647/10554647_20210127173809_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>
 </div></td>
 <td><div class="wrap">
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=33241003" title="그대 작은 나의 세상이 되어 곡정보"><span class="none">곡정보</span></a>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank01"><span>
 <a href="javascript:melon.play.playSong('1000002721',33241003);" title="그대 작은 나의 세상이 되어 재생">그대 작은 나의 세상이 되어</a>
 </span></div><br/>
 <div class="ellipsis rank02">
 <a href="/artist/timeline.htm?artistId=735506" title="카더가든 - 페이지 이동">카더가든</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=735506" title="카더가든 - 페이지 이동">카더가든</a></span>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <div class="wrap_song_info">
 <div class="ellipsis rank03">
 <a href="/album/detail.htm?albumId=10554647" title="부재 - 페이지 이동">부재</a>
 </div>
 </div>
 </div></td>
 <td><div class="wrap">
 <button class="button_etc like" data-song-menuid="1000002721" data-song-no="33241003" title="그대 작은 나의 세상이 되어 좋아요" type="button"><span class="odd_span">좋아요</span>
 <span class="cnt">
 <span class="none">총건수</span>
 75,395</span></button>
 </div></td>
 <td><div class="wrap t_center">
 <button class="button_icons play" onclick="melon.play.playSong('1000002721',33241003);" title="듣기" type="button"><span class="none">듣기</span></button>
 </div></td>
 <td><div class="wrap t_center">

In [32]:
len(lst)

50

In [33]:
lst[-1]

<tr class="lst50" data-song-no="38120327" id="lst50">
<td><div class="wrap t_right"><input class="input_check" name="input_check" title="APT. 곡 선택" type="checkbox" value="38120327"/></div></td>
<td><div class="wrap t_center"><span class="rank">50</span><span class="none">위</span></div></td>
<!-- 차트순위 추가 -->
<td><div class="wrap">
<span class="rank_wrap" title="2단계 상승">
<span class="bullet_icons rank_up"><span class="none">단계 상승</span></span>
<span class="up">2</span>
</span>
</div></td>
<td><div class="wrap">
<a class="image_typeAll" href="/album/detail.htm?albumId=11619809" title="APT.">
<img alt="APT. - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/116/19/809/11619809_20241018103507_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
<span class="bg_album_frame"></span>
</a>
</div></td>
<td><div class="wrap">
<a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=38120327" title="APT. 곡정보"><span class="none">곡정보</span></a>
</div></td>
<td><div class="wrap">
<div class="wrap_song_info">
<div class="ellipsis rank01"><span>
<a href="javascript:melon.play.playSong('1000002721',38120327);" title="APT. 재생">APT.</a>
</span></div><br/>
<div class="ellipsis rank02">
<a href="/artist/timeline.htm?artistId=995171" title="로제 (ROSÉ) - 페이지 이동">로제 (ROSÉ)</a>, <a href="/artist/timeline.htm?artistId=495811" title="Bruno Mars - 페이지 이동">Bruno Mars</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=995171" title="로제 (ROSÉ) - 페이지 이동">로제 (ROSÉ)</a>, <a href="/artist/timeline.htm?artistId=495811" title="Bruno Mars - 페이지 이동">Bruno Mars</a></span>
</div>
<div class="wrap_atist" style="display:none;">
<button class="button_icons etc more_down" data-control="dropdown" title="아티스트 더보기" type="button"><span class="none">아티스트명 더보기</span></button>
<div class="atist_view" style="display:none;">
<ul>
<li><a class="ellipsis" href="/artist/timeline.htm?artistId=995171" title="로제 (ROSÉ) 페이지 이동">로제 (ROSÉ)</a></li>
<li><a class="ellipsis" href="/artist/timeline.htm?artistId=495811" title="Bruno Mars 페이지 이동">Bruno Mars</a></li>
</ul>
</div>
</div>
</div>
</div></td>
<td><div class="wrap">
<div class="wrap_song_info">
<div class="ellipsis rank03">
<a href="/album/detail.htm?albumId=11619809" title="APT. - 페이지 이동">APT.</a>
</div>
</div>
</div></td>
<td><div class="wrap">
<button class="button_etc like" data-song-menuid="1000002721" data-song-no="38120327" title="APT. 좋아요" type="button"><span class="odd_span">좋아요</span>
<span class="cnt">
<span class="none">총건수</span>
220,044</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons play" onclick="melon.play.playSong('1000002721',38120327);" title="듣기" type="button"><span class="none">듣기</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons scrap" onclick="melon.play.addPlayList('38120327');" title="담기" type="button"><span class="none">담기</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '38120327', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons video" onclick="melon.link.goMvDetail('1000002721', '38120327','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
</div></td>
</tr>

In [34]:
# 1위~50위: tr.lst50
# 51위~100위: tr.lst100

lst50 = soup.select('tr.lst50')
lst100 = soup.select('tr.lst100')

lst = lst50 + lst100

In [35]:
len(lst)

100

In [36]:
# 8. 정보 뭉치 1개에서 우리가 원하는 정보 찾기
element = lst[0]
element

<tr class="lst50" data-song-no="601237102" id="lst50">
<td><div class="wrap t_right"><input class="input_check" name="input_check" title="BANG BANG 곡 선택" type="checkbox" value="601237102"/></div></td>
<td><div class="wrap t_center"><span class="rank">1</span><span class="none">위</span></div></td>
<!-- 차트순위 추가 -->
<td><div class="wrap">
<span class="rank_wrap" title="순위 동일">
<span class="bullet_icons rank_static"><span class="none">순위 동일</span></span>
<span class="none">0</span>
</span>
</div></td>
<td><div class="wrap">
<a class="image_typeAll" href="/album/detail.htm?albumId=12845274" title="REVIVE+">
<img alt="REVIVE+ - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/128/45/274/12845274_20260223113048_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
<span class="bg_album_frame"></span>
</a>
</div></td>
<td><div class="wrap">
<a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=601237102" title="BANG BANG 곡정보"><span class="none">곡정보</span></a>
</div></td>
<td><div class="wrap">
<div class="wrap_song_info">
<div class="ellipsis rank01"><span>
<a href="javascript:melon.play.playSong('1000002721',601237102);" title="BANG BANG 재생">BANG BANG</a>
</span></div><br/>
<div class="ellipsis rank02">
<a href="/artist/timeline.htm?artistId=3055146" title="IVE (아이브) - 페이지 이동">IVE (아이브)</a><span class="checkEllipsis" style="display: none;"><a href="/artist/timeline.htm?artistId=3055146" title="IVE (아이브) - 페이지 이동">IVE (아이브)</a></span>
</div>
</div>
</div></td>
<td><div class="wrap">
<div class="wrap_song_info">
<div class="ellipsis rank03">
<a href="/album/detail.htm?albumId=12845274" title="REVIVE+ - 페이지 이동">REVIVE+</a>
</div>
</div>
</div></td>
<td><div class="wrap">
<button class="button_etc like" data-song-menuid="1000002721" data-song-no="601237102" title="BANG BANG 좋아요" type="button"><span class="odd_span">좋아요</span>
<span class="cnt">
<span class="none">총건수</span>
45,547</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons play" onclick="melon.play.playSong('1000002721',601237102);" title="듣기" type="button"><span class="none">듣기</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons scrap" onclick="melon.play.addPlayList('601237102');" title="담기" type="button"><span class="none">담기</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons download" onclick="melon.buy.goBuyProduct('frm', '601237102', '3C0001', '','0', '1000002721');" title="다운로드" type="button"><span class="none">다운로드</span></button>
</div></td>
<td><div class="wrap t_center">
<button class="button_icons video" onclick="melon.link.goMvDetail('1000002721', '601237102','song');" title="뮤직비디오" type="button"><span class="none">뮤직비디오</span></button>
</div></td>
</tr>

In [38]:
ranking = element.select('span.rank')
ranking # 리스트 타입의 객체

In [39]:
# 리스트 타입의 객체에서 첫번째 원소 선택하기
ranking = element.select('span.rank')[0]
ranking

In [40]:
ranking = element.select('span.rank')[0].text
ranking

'1'

In [41]:
# 노래 제목 찾기 - a 태그에서 좀 더 정확한 태그 찾기 
song_name = element.select('span > a')
song_name

[<a href="javascript:melon.play.playSong('1000002721',601237102);" title="BANG BANG 재생">BANG BANG</a>,
 <a href="/artist/timeline.htm?artistId=3055146" title="IVE (아이브) - 페이지 이동">IVE (아이브)</a>]

In [44]:
# 노래 제목 찾기 - a 태그에서 좀 더 정확한 태그 찾기 
song_name = element.select('div.ellipsis.rank01 > span > a')
song_name

In [45]:
# 노래 제목 찾기 - 첫 번째 원소를 선택하기 
song_name = element.select('div.ellipsis.rank01 > span > a')[0]
song_name

In [46]:
# 노래 제목 찾기 - 텍스트 부분 추출하기
song_name = element.select('div.ellipsis.rank01 > span > a')[0].text
song_name

'BANG BANG'

In [48]:
# 가수 이름 찾기 - 1) a 태그 찾기
singer = element.select('a')
singer

[<a class="image_typeAll" href="/album/detail.htm?albumId=12845274" title="REVIVE+">
 <img alt="REVIVE+ - 페이지 이동" height="60" onerror="WEBPOCIMG.defaultAlbumImg(this);" src="https://cdnimg.melon.co.kr/cm2/album/images/128/45/274/12845274_20260223113048_500.jpg/melon/resize/120/quality/80/optimize" width="60"/>
 <span class="bg_album_frame"></span>
 </a>,
 <a class="btn button_icons type03 song_info" href="/song/detail.htm?songId=601237102" title="BANG BANG 곡정보"><span class="none">곡정보</span></a>,
 <a href="javascript:melon.play.playSong('1000002721',601237102);" title="BANG BANG 재생">BANG BANG</a>,
 <a href="/artist/timeline.htm?artistId=3055146" title="IVE (아이브) - 페이지 이동">IVE (아이브)</a>,
 <a href="/artist/timeline.htm?artistId=3055146" title="IVE (아이브) - 페이지 이동">IVE (아이브)</a>,
 <a href="/album/detail.htm?albumId=12845274" title="REVIVE+ - 페이지 이동">REVIVE+</a>]

In [51]:
# 가수 이름 찾기 - 2) a 태그 찾기 (원하는 정보만 찾기)
singer = element.select('div.ellipsis.rank02 > a')
singer

In [52]:
# 가수 이름 찾기 - 3) 첫번째 원소 추출하기
singer = element.select('div.ellipsis.rank02 > a')[0]
singer

In [53]:
# 가수 이름 찾기 - 4) 텍스트 추출하기
singer = element.select('div.ellipsis.rank02 > a')[0].text
singer

'IVE (아이브)'

In [55]:
# 앨범제목 찾기
album_name = element.select('div.ellipsis.rank03 > a')[0].text
album_name

'REVIVE+'

In [57]:
# 좋아요 숫자 찾기
like_count = element.select('span.cnt')[0].text
like_count

'\n총건수\n45,547'

In [58]:
# 좋아요 숫자 찾기 - 우리가 원하는 부분 찾기
like_count = element.select('span.cnt')[0].text.split('\n')
like_count

['', '총건수', '45,547']

In [59]:
# 좋아요 숫자 찾기 - 우리가 원하는 부분 찾기 (리스트에서 세번째 원소 선택하기)
like_count = element.select('span.cnt')[0].text.split('\n')[2]
like_count

'45,547'

In [60]:
element_result = [ranking, song_name, singer, album_name, like_count]
element_result

['1', 'BANG BANG', 'IVE (아이브)', 'REVIVE+', '45,547']

In [61]:
# 정보 뭉치에서 정보찾는 것 반복하기
result = []

for element in lst:
    ranking = element.select('span.rank')[0].text
    song_name = element.select('div.ellipsis.rank01 > span > a')[0].text
    singer = element.select('div.ellipsis.rank02 > a')[0].text
    album_name = element.select('div.ellipsis.rank03 > a')[0].text
    like_count = element.select('span.cnt')[0].text.split('\n')[2]

    element_result = [ranking, song_name, singer, album_name, like_count]

    result.append(element_result)

In [62]:
result

[['1', 'BANG BANG', 'IVE (아이브)', 'REVIVE+', '45,547'],
 ['2', '404 (New Era)', 'KiiiKiii (키키)', 'Delulu Pack', '46,528'],
 ['3', 'Good Goodbye', '화사 (HWASA)', 'Good Goodbye', '113,432'],
 ['4', 'RUDE!', 'Hearts2Hearts (하츠투하츠)', 'RUDE!', '27,232'],
 ['5', '사랑하게 될 거야', '한로로', '이상비행', '110,317'],
 ['6', 'Drowning', 'WOODZ', 'OO-LI', '289,189'],
 ['7', '그대 작은 나의 세상이 되어', '카더가든', '부재', '75,395'],
 ['8', '0+0', '한로로', '자몽살구클럽', '76,279'],
 ['9', '타임캡슐', '다비치', '타임캡슐', '62,454'],
 ['10', 'BLACKHOLE', 'IVE (아이브)', 'REVIVE+', '25,334'],
 ['11', 'Blue Valentine', 'NMIXX', 'Blue Valentine', '110,741'],
 ['12', '멸종위기사랑', '이찬혁', 'EROS', '85,011'],
 ['13',
  'Golden',
  'HUNTR/X',
  'KPop Demon Hunters (Soundtrack from the Netflix Film)',
  '190,826'],
 ['14', '어제보다 슬픈 오늘', '우디 (Woody)', '어제보다 슬픈 오늘', '80,984'],
 ['15', '뛰어(JUMP)', 'BLACKPINK', '뛰어(JUMP)', '93,796'],
 ['16', 'GO', 'BLACKPINK', 'DEADLINE', '14,557'],
 ['17',
  'SPAGHETTI (feat. j-hope of BTS)',
  'LE SSERAFIM (르세라핌)',
  'SPAGHETTI',
  '47,998'],
 ['18', 'NOT CUTE ANYMORE', '아일릿(ILLIT)', 'NOT CUTE ANYMORE', '43,544'],
 ['19', 'toxic till the end', '로제 (ROSÉ)', 'rosie', '148,121'],
 ['20', '모르시나요(PROD.로코베리)', '조째즈', '모르시나요', '105,086'],
 ['21', 'ONE MORE TIME', 'ALLDAY PROJECT', 'ALLDAY PROJECT', '58,511'],
 ['22', '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 'AKMU (악뮤)', '항해', '492,833'],
 ['23', '사랑은 봄비처럼...이별은 겨울비처럼...', '임현정', 'All That Love', '59,364'],
 ['24', '너의 모든 순간', '성시경', '별에서 온 그대 OST Part.7', '318,976'],
 ['25', '달리 표현할 수 없어요', '로이킴', '달리 표현할 수 없어요', '37,760'],
 ['26', 'like JENNIE', '제니 (JENNIE)', 'Ruby', '107,733'],
 ['27', '내게 사랑이 뭐냐고 물어본다면', '로이킴', '내게 사랑이 뭐냐고 물어본다면', '93,241'],
 ['28', '천상연', '이창섭', "천상연 (웹툰 '선녀외전' X 이창섭 (LEE CHANGSUB))", '143,840'],
 ['29', '사랑은 늘 도망가', '임영웅', '신사와 아가씨 OST Part.2', '236,531'],
 ['30',
  'HOME SWEET HOME (feat. 태양, 대성)',
  'G-DRAGON',
  'HOME SWEET HOME (feat. 태양, 대성)',
  '228,625'],
 ['31', '너에게 닿기를', '10CM', '너에게 닿기를', '142,934'],
 ['32',
  'Love Love Love (Feat. Yoong Jin Of Casker)',
  '에픽하이 (EPIK HIGH)',
  'Remapping The Human Soul',
  '113,545'],
 ['33',
  'FOCUS',
  'Hearts2Hearts (하츠투하츠)',
  'FOCUS - The 1st Mini Album',
  '37,986'],
 ['34', 'FAMOUS', 'ALLDAY PROJECT', 'FAMOUS', '129,950'],
 ['35', 'Whiplash', 'aespa', 'Whiplash - The 5th Mini Album', '151,330'],
 ['36', 'OVERDRIVE', 'TWS (투어스)', 'TWS 4th Mini Album ‘play hard’', '38,739'],
 ['37', 'REBEL HEART', 'IVE (아이브)', 'IVE EMPATHY', '118,736'],
 ['38', 'STYLE', 'Hearts2Hearts (하츠투하츠)', 'STYLE', '55,201'],
 ['39', '나는 반딧불', '황가람', '나는 반딧불', '157,499'],
 ['40',
  '모든 날, 모든 순간 (Every day, Every Moment)',
  '폴킴',
  "'키스 먼저 할까요?' OST Part.3",
  '438,425'],
 ['41', '청춘만화', '이무진', '만화 (滿花)', '96,400'],
 ['42',
  '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))',
  '너드커넥션 (Nerd Connection)',
  '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))',
  '168,948'],
 ['43',
  '힙합보단 사랑, 사랑보단 돈 (Feat. 베이식)',
  '노아주다 (noahjooda)',
  'M O T N O A H',
  '48,345'],
 ['44', 'HAPPY', 'DAY6 (데이식스)', 'Fourever', '210,079'],
 ['45', '소나기', '이클립스 (ECLIPSE)', '선재 업고 튀어 OST Part 1', '192,902'],
 ['46', '시작의 아이 ❍', '박다혜', '시작의 아이 ❍ ハジマリのコ Starting With You : ♡', '67,894'],
 ['47', '한 페이지가 될 수 있게', 'DAY6 (데이식스)', 'The Book of Us : Gravity', '365,056'],
 ['48', '예뻤어', 'DAY6 (데이식스)', 'Every DAY6 February', '378,827'],
 ['49', '하얀 그리움', '프로미스나인', '하얀 그리움', '37,274'],
 ['50', 'APT.', '로제 (ROSÉ)', 'APT.', '220,044'],
 ['51',
  '첫 만남은 계획대로 되지 않아',
  'TWS (투어스)',
  'TWS 1st Mini Album ‘Sparkling Blue’',
  '171,788'],
 ['52', '오늘만 I LOVE YOU', 'BOYNEXTDOOR', '오늘만 I LOVE YOU', '183,302'],
 ['53',
  'Soda Pop',
  'KPop Demon Hunters Cast',
  'KPop Demon Hunters (Soundtrack from the Netflix Film)',
  '116,026'],
 ['54', 'XOXZ', 'IVE (아이브)', 'IVE SECRET', '54,373'],
 ['55', '끝사랑', '테이', '끝사랑', '8,559'],
 ['56', 'Flower', '오반(OVAN)', '교회오빠', '82,136'],
 ['57', 'Love wins all', '아이유', 'The Winning', '220,971'],
 ['58', 'Welcome to the Show', 'DAY6 (데이식스)', 'Fourever', '195,114'],
 ['59', '사랑인가 봐', '멜로망스', '사랑인가 봐 (사내맞선 OST 스페셜 트랙)', '234,311'],
 ['60', '주저하는 연인들을 위해', '잔나비', '전설', '452,395'],
 ['61',
  '시작의 아이',
  '마크툽 (MAKTUB)',
  '시작의 아이 ハジマリのコ (Starting With You)',
  '84,104'],
 ['62', '순간을 영원처럼', '임영웅', 'IM HERO 2', '47,579'],
 ['63', '청혼하지 않을 이유를 못 찾았어', '이무진', '청혼하지 않을 이유를 못 찾았어', '70,376'],
 ['64', 'Die With A Smile', 'Lady Gaga', 'Die With A Smile', '131,644'],
 ['65', '우리들의 블루스', '임영웅', 'IM HERO', '124,960'],
 ['66', 'I AM', 'IVE (아이브)', "I've IVE", '237,390'],
 ['67', '그래 늦지 않았어 (2025)', '아샤트리', '그래 늦지 않았어(2025)', '13,980'],
 ['68',
  '사랑의 언어 (Love Language)',
  '김민석 (멜로망스)',
  '이 사랑 통역 되나요? (Soundtrack from the Netflix Series)',
  '18,495'],
 ['69', '다정히 내 이름을 부르면', '경서예지', '다정히 내 이름을 부르면 (경서예지 x 전건호)', '221,903'],
 ['70',
  'Daydream',
  '웬디 (WENDY)',
  '이 사랑 통역 되나요? (Soundtrack from the Netflix Series)',
  '13,923'],
 ['71', '다시 만날 수 있을까', '임영웅', 'IM HERO', '102,998'],
 ['72', 'Never Ending Story', '아이유', '꽃갈피 셋', '84,413'],
 ['73', '헤어지자 말해요', '박재정', '1집 Alone', '192,657'],
 ['74', '운명 (2025)', '먼데이 키즈', '먼키의 발자국 Vol.1 With 이이경', '34,803'],
 ['75', 'Magnetic', '아일릿(ILLIT)', 'SUPER REAL ME', '143,724'],
 ['76', '한번 더 이별', '이창섭', '한번 더 이별 (첫사랑 엔딩 X 이창섭)', '32,102'],
 ['77', 'TOO BAD (feat. Anderson .Paak)', 'G-DRAGON', 'Übermensch', '155,103'],
 ['78', '눈사람', '정승환', '그리고 봄', '307,902'],
 ['79',
  'Zoo (From "Zootopia 2"/Soundtrack Version)',
  'Disney',
  'Zoo (From "Zootopia 2")',
  '34,407'],
 ['80', '인사', '범진', '인사', '160,907'],
 ['81', '365일', '이창섭', '365일 (오늘 밤, 세계에서 이 사랑이 사라진다 해도 X 이창섭)', '13,295'],
 ['82', 'Hype Boy', 'NewJeans', "NewJeans 1st EP 'New Jeans'", '314,511'],
 ['83', 'Rich Man', 'aespa', 'Rich Man - The 6th Mini Album', '51,030'],
 ['84',
  'Seven (feat. Latto) - Clean Ver.',
  '정국',
  'Seven (feat. Latto) - Clean Ver.',
  '228,575'],
 ['85', '비의 랩소디', '임재현', '비의 랩소디', '108,735'],
 ['86', '들꽃이 될게요', '임영웅', 'IM HERO 2', '38,212'],
 ['87', 'Supernova', 'aespa', 'Armageddon - The 1st Album', '186,892'],
 ['88', 'MY LOVE(2025)', '이예은', 'MY LOVE(2025)', '38,359'],
 ['89', '다시 만난 오늘', 'TWS (투어스)', '다시 만난 오늘', '18,771'],
 ['90', 'IRIS OUT', 'Kenshi Yonezu', 'IRIS OUT', '76,726'],
 ['91', '빌려온 고양이 (Do the Dance)', '아일릿(ILLIT)', 'bomb', '56,508'],
 ['92', '에피소드', '이무진', '에피소드', '139,655'],
 ['93',
  '이 밤을 빌려 말해요',
  'PLAVE',
  '이 밤을 빌려 말해요 (오늘 밤, 세계에서 이 사랑이 사라진다 해도 X PLAVE)',
  '22,296'],
 ['94', '슬픈 초대장', '순순희(지환)', '슬픈 초대장', '78,061'],
 ['95', 'Dirty Work', 'aespa', 'Dirty Work', '67,975'],
 ['96', 'Hollywood Action', 'BOYNEXTDOOR', 'The Action', '57,929'],
 ['97', '그댈 위한 멜로디', '임영웅', 'IM HERO 2', '38,220'],
 ['98', '고민중독', 'QWER', "1st Mini Album 'MANITO'", '155,102'],
 ['99', '눈이 오잖아(Feat.헤이즈)', '이무진', '눈이 오잖아(Feat.헤이즈)', '171,017'],
 ['100', '가만히 눈을 감고', 'DK(디셈버)', '가만히 눈을 감고', '20,763']]

In [63]:
# 보기 좋게 표 형태로 변경
result_df = pd.DataFrame(result)
result_df

,0,1,2,3,4
0,1,BANG BANG,IVE (아이브),REVIVE+,"45,547"
1,2,404 (New Era),KiiiKiii (키키),Delulu Pack,"46,528"
2,3,Good Goodbye,화사 (HWASA),Good Goodbye,"113,432"
3,4,RUDE!,Hearts2Hearts (하츠투하츠),RUDE!,"27,232"
4,5,사랑하게 될 거야,한로로,이상비행,"110,317"
...,...,...,...,...,...
95,96,Hollywood Action,BOYNEXTDOOR,The Action,"57,929"
96,97,그댈 위한 멜로디,임영웅,IM HERO 2,"38,220"
97,98,고민중독,QWER,1st Mini Album 'MANITO',"155,102"
98,99,눈이 오잖아(Feat.헤이즈),이무진,눈이 오잖아(Feat.헤이즈),"171,017"
99,100,가만히 눈을 감고,DK(디셈버),가만히 눈을 감고,"20,763"

In [64]:
columns_name = ['랭킹', '제목', '가수', '앨범명', '좋아요 수']
result_df = pd.DataFrame(result, columns=columns_name)
result_df

,랭킹,제목,가수,앨범명,좋아요 수
0,1,BANG BANG,IVE (아이브),REVIVE+,"45,547"
1,2,404 (New Era),KiiiKiii (키키),Delulu Pack,"46,528"
2,3,Good Goodbye,화사 (HWASA),Good Goodbye,"113,432"
3,4,RUDE!,Hearts2Hearts (하츠투하츠),RUDE!,"27,232"
4,5,사랑하게 될 거야,한로로,이상비행,"110,317"
...,...,...,...,...,...
95,96,Hollywood Action,BOYNEXTDOOR,The Action,"57,929"
96,97,그댈 위한 멜로디,임영웅,IM HERO 2,"38,220"
97,98,고민중독,QWER,1st Mini Album 'MANITO',"155,102"
98,99,눈이 오잖아(Feat.헤이즈),이무진,눈이 오잖아(Feat.헤이즈),"171,017"
99,100,가만히 눈을 감고,DK(디셈버),가만히 눈을 감고,"20,763"

In [65]:
# 10. 엑셀파일로 저장하기
result_df.to_excel('melon_top100.xlsx')